### PR TITLE
Added Python 3 compatibility

### PR DESCRIPTION
**Pull request by tweakdeveloper**
When I tried to use your library with Python 3 it threw several errors, but I changed the import statements to work with both Python 2 and 3. I'd really appreciate it if you could add this functionality! :smile:

### CODE REVIEW

**Comment by tweakdeveloper** [comment]
Oh wait, I've just discovered a new problem.

**Comment by tweakdeveloper** [comment]
There we go, everything appears to be in order now.

**Comment by juliomalegria** [comment]
Thanks for contributing @tweakdeveloper. Looks good!
Two things though:
* Instead of doing a try/catch in the relative import, could you do this: `from __future__ import absolute_import`? I think that's a cleaner workaround. That way we use `from sites import whatever` for both py2 and py3.
* Could you add comments in the two other try/catches (`#PY2` / `#PY3`) just for people to understand why they're there.

Thanks!

**Comment by tweakdeveloper** [comment]
Sure thing! I'll fix it right when I get home.

**Comment by juliomalegria** [comment]
Thanks for contributing @tweakdeveloper

**Pull request merged**
