### PR TITLE
Add min bedroom/bathroom flags to CraigslistHousing

### PR DESCRIPTION
**Pull request by vpontis**
This code allows the following example to work.

```from craigslist import CraigslistHousing
cl_h = CraigslistHousing(site='sfbay', area='sfc', category='apa',
                         filters={'min_price': 6000, 'min_bedrooms': 5, 'min_bathrooms': 2})

for result in cl_h.get_results(sort_by='newest', geotagged=True):
    print(result)
```

### CODE REVIEW

**Comment by juliomalegria** [comment]
Thanks Victor! Would you mind adding 'max_bedrooms' and 'max_bathrooms' as well? Also removing the (apparently now deprecated) 'bedrooms' and 'bathrooms' (a couple of lines under your changes).

Thanks for contributing!

**Comment by vpontis** [comment]
Yep, I'll do that soon!

Question: do you have a script that you use to package up `python-craigslist` for `pip`?

It might also be nice to have a tag/branch for each version. I wanted to add these changes to `1.0.3` but it was a little confusing at first since there is no tag/branch for the version.

**Comment by juliomalegria** [comment]
This was done in 0794bad.

**Comment by juliomalegria** [comment]
I've been wanting to add tags or branches for the different versions, but I still haven't done. I'll look into it. I think it's a great idea 👍

**Comment by vpontis** [comment]
Thanks for getting this done @juliomalegria!

**Comment by vpontis** [comment]
I have some other ideas for ways of automating things on Craigslist... So I might be back and contributing to this repo again soon :)

**Pull request closed without merging**
