### PR TITLE
improved docs

### PR DESCRIPTION
**Pull request by Debosmit-Neogi**

### CODE REVIEW

**Comment by juliomalegria** [comment]
Amazing! Thank you for those fixes.

**Comment by Debosmit-Neogi** [comment]
I am glad it worked for you.

**Comment by juliomalegria** [comment]
Hey Debosmit,
I was curious about how did you find out about this project and decided to contribute? I recently received a lot of requests for this repo and I was wondering if they were connected.
Thanks again!

**Comment by Debosmit-Neogi** [comment]
Hello Julio,
Actually I was going through some python based projects' repos. And I came across your repo and I found your work really interesting. So, I surfed through all your works and I don't think all the requests  that you are getting lately are anyways connected.
Thank you.

**Pull request merged**
